// File System Access adapters validate resumability; this is not browser/device QA.
import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');const code=source.slice(source.indexOf('function backupSnapshot'),source.indexOf("$('folder-backup').addEventListener('click'"));
function directory(){const files=new Map(),dirs=new Map();return {files,dirs,async getDirectoryHandle(name){if(!dirs.has(name))dirs.set(name,directory());return dirs.get(name);},async getFileHandle(name,{create=false}={}){if(!files.has(name)){if(!create)throw new DOMException('Missing','NotFoundError');files.set(name,new Uint8Array());}return {async getFile(){return new Blob([files.get(name)]);},async createWritable(){let chunks=[];const stream=new WritableStream({write(chunk){chunks.push(typeof chunk==='string'?new TextEncoder().encode(chunk):new Uint8Array(chunk));},close(){const size=chunks.reduce((n,b)=>n+b.length,0),bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}files.set(name,bytes);}});stream.write=async chunk=>{chunks.push(typeof chunk==='string'?new TextEncoder().encode(chunk):new Uint8Array(chunk));};stream.close=async()=>{await stream.getWriter().close();};stream.abort=async()=>{chunks=[];};return stream;}};}};}
const books=[{id:'one',status:'ready',title:'one',file_size:10,indexed_pages:1},{id:'two',status:'ready',title:'two',file_size:10,indexed_pages:1}];let metadata={format:'pdf-page-finder-backup',version:1,books,shelves:[]};
let root=directory(),chosen=root,fail=true,downloads=[];const elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id);};
const context=vm.createContext({window:{showDirectoryPicker:async()=>chosen},$,backingUp:false,backupController:null,AbortController,DOMException,JSON,Date,Error,console,api:async path=>path==='/api/account/export'?structuredClone(metadata):{pages:[{number:1,body:'test',normalized:'test'}],next:1,hasMore:false},fetch:async path=>{downloads.push(path);if(path.endsWith('two/file')&&fail){fail=false;throw Error('simulated disconnect');}return new Response(new Uint8Array(10));}});vm.runInContext(code,context);
await context.saveFolderBackup(false);const saved=[...root.dirs.values()][0];assert(saved.files.has('one.complete.json'));assert(!saved.files.has('COMPLETE.json'));
chosen=saved;await context.saveFolderBackup(true);assert(saved.files.has('COMPLETE.json'));assert.equal(downloads.filter(p=>p.endsWith('one/file')).length,1);
const count=downloads.length;await context.saveFolderBackup(true);assert.equal(downloads.length,count);assert($('data-status').textContent.includes('完了済み'));
root=directory();chosen=root;fail=true;await context.saveFolderBackup(false);chosen=[...root.dirs.values()][0];metadata={...metadata,books:books.map(b=>({...b,title:b.title+'changed'}))};const before=downloads.length;await context.saveFolderBackup(true);assert.equal(downloads.length,before);assert(!chosen.files.has('COMPLETE.json'));assert($('data-status').textContent.includes('状態が変わっています'));
console.log('Folder backup adapters: interrupted save, completed-book skip, resume and snapshot change rejection passed');
