import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
const ts=createRequire(import.meta.url)('typescript');
const source=readFileSync(new URL('../app/api/library/shared.ts',import.meta.url),'utf8');
const exports={};vm.runInNewContext(ts.transpileModule(source.slice(source.indexOf('export function expectedLengthBody'),source.indexOf('export function serverError')),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,ReadableStream,RangeError});
const {expectedLengthBody}=exports;
let cancelled=false;
const oversize=new ReadableStream({start(c){c.enqueue(new Uint8Array(9));},cancel(){cancelled=true;}});
await assert.rejects(new Response(expectedLengthBody(oversize,8)).arrayBuffer(),/length exceeded/);assert(cancelled);assert.equal(oversize.locked,false);
const short=new ReadableStream({start(c){c.enqueue(new Uint8Array(7));c.close();}});
await assert.rejects(new Response(expectedLengthBody(short,8)).arrayBuffer(),/length mismatch/);assert.equal(short.locked,false);
const valid=new ReadableStream({start(c){c.enqueue(new Uint8Array([1,2]));c.enqueue(new Uint8Array([3]));c.close();}});
assert.deepEqual(new Uint8Array(await new Response(expectedLengthBody(valid,3)).arrayBuffer()),new Uint8Array([1,2,3]));assert.equal(valid.locked,false);
const broken=new ReadableStream({pull(c){c.error(Error('network disconnected'));}});
await assert.rejects(new Response(expectedLengthBody(broken,8)).arrayBuffer(),/network disconnected/);assert.equal(broken.locked,false);
let consumerCancelled=false;const waiting=new ReadableStream({cancel(){consumerCancelled=true;}});
await expectedLengthBody(waiting,8).cancel('stopped');assert(consumerCancelled);assert.equal(waiting.locked,false);
console.log('Upload stream: actual length limits, short body, disconnect, cancellation and reader release passed');
